// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzrdM4pPPiItJcqlXzIlo1bheQevBsGnM',
    appId: '1:461730521639:web:1ccfa85d2e2a9a6a17e402',
    messagingSenderId: '461730521639',
    projectId: 'todo-list006',
    authDomain: 'todo-list006.firebaseapp.com',
    databaseURL: 'https://todo-list006-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-list006.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4QIy-3PP4I55tPp93XSlIWykIWSKE1DI',
    appId: '1:461730521639:android:ff88fc3cffc00d4f17e402',
    messagingSenderId: '461730521639',
    projectId: 'todo-list006',
    databaseURL: 'https://todo-list006-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-list006.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzrdM4pPPiItJcqlXzIlo1bheQevBsGnM',
    appId: '1:461730521639:web:95805ace8b2c262e17e402',
    messagingSenderId: '461730521639',
    projectId: 'todo-list006',
    authDomain: 'todo-list006.firebaseapp.com',
    databaseURL: 'https://todo-list006-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-list006.firebasestorage.app',
  );
}
